// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIoJM_A2AIKKGf0pxjXzsFhXaBl8OL7qg',
    appId: '1:334903237317:web:cd5fdf0a136b6bc2efeeac',
    messagingSenderId: '334903237317',
    projectId: 'example-92821',
    authDomain: 'example-92821.firebaseapp.com',
    storageBucket: 'example-92821.firebasestorage.app',
    measurementId: 'G-Q1SZN5N3B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmrZN-aJ4rl67v3QznqF0Udtx_26MpJfw',
    appId: '1:334903237317:android:01251c963abb1e8aefeeac',
    messagingSenderId: '334903237317',
    projectId: 'example-92821',
    storageBucket: 'example-92821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtNyy_qKLd5KiT1620DpWZUybQmxi4kqE',
    appId: '1:334903237317:ios:1fb2d9331bd07c24efeeac',
    messagingSenderId: '334903237317',
    projectId: 'example-92821',
    storageBucket: 'example-92821.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtNyy_qKLd5KiT1620DpWZUybQmxi4kqE',
    appId: '1:334903237317:ios:1fb2d9331bd07c24efeeac',
    messagingSenderId: '334903237317',
    projectId: 'example-92821',
    storageBucket: 'example-92821.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIoJM_A2AIKKGf0pxjXzsFhXaBl8OL7qg',
    appId: '1:334903237317:web:147530ec1ac470aaefeeac',
    messagingSenderId: '334903237317',
    projectId: 'example-92821',
    authDomain: 'example-92821.firebaseapp.com',
    storageBucket: 'example-92821.firebasestorage.app',
    measurementId: 'G-84JE59GCSV',
  );
}
